export const validURLS = [
  'http://stackoverflow.com/',
  'https://stackoverflow.com',
  'http://stackoverflow.com/',
  'http://stackoverflow.com',
  'http://www.stackoverflow.com/',
  'http://www.stackoverflow.com',
  'www.stackoverflow.com/',
  'www.stackoverflow.com',
  'ichbineineurl.de',
  'ichbineineurl.de/',
  'ichbineineurl.de.vu/links',
  // more
  'http://foo.com/blah_blah',
  'http://foo.com/blah_blah/',
  'http://foo.com/blah_blah_(wikipedia)',
  'http://foo.com/blah_blah_(wikipedia)_(again)',
  'http://www.example.com/wpstyle/?p=364',
  'https://www.example.com/foo/?bar=baz&inga=42&quux',
  'http://✪df.ws/123',
  'http://userid:password@example.com:8080',
  'http://userid:password@example.com:8080/',
  'http://userid@example.com',
  'http://userid@example.com/',
  'http://userid@example.com:8080',
  'http://userid@example.com:8080/',
  'http://userid:password@example.com',
  'http://userid:password@example.com/',
  'http://142.42.1.1/',
  'http://142.42.1.1:8080/',
  'http://➡.ws/䨹',
  'http://⌘.ws',
  'http://⌘.ws/',
  'http://foo.com/blah_(wikipedia)#cite-1',
  'http://foo.com/blah_(wikipedia)_blah#cite-1',
  'http://foo.com/unicode_(✪)_in_parens',
  'http://foo.com/(something)?after=parens',
  'http://☺.damowmow.com/',
  'http://code.google.com/events/#&product=browser',
  'http://j.mp',
  'ftp://foo.bar/baz',
  'http://foo.bar/?q=Test%20URL-encoded%20stuff',
  'http://مثال.إختبار',
  'http://例子.测试',
  'http://उदाहरण.परीक्षा',
  'http://1337.net',
  'http://a.b-c.de',
  'http://223.255.255.254',
  'gabriel@nand.io',
];

export const invalidURLS = [
  'hallo:hallo.de',
  'http:://www.ASDASDASD.XASDASDASD',
  'hjttp:/asd.w',
  'soundcloud',
  'youtube',
  'vimeo',
  'vim',
  'http://',
  'http://.',
  'http://..',
  'http://../',
  'http://?',
  'http://??',
  'http://??/',
  'http://#',
  'http://##',
  'http://##/',
  'http://foo.bar?q=Spaces should be encoded',
  'http:// shouldfail.com',
  'http://foo.bar/foo(bar)baz quux',
  'http://-error-.invalid/',
  'http://-a.b.co',
  'http://a.b-.co',
  'http://0.0.0.0',
  'http://10.1.1.0',
  'http://10.1.1.255',
  'http://224.1.1.1',
  'http://1.1.1.1.1',
  'http://123.123.123',
  'http://3628126748',
  'http://.www.foo.bar/',
  'http://.www.foo.bar./',
  'http://10.1.1.1',
];

/*
 * taken from: https://gist.github.com/Glurt/ea11b690ba4b1278e049
 */
export const youtubeURLS = [
  'http://www.youtube.com/watch?v=kszLwBaC4Sw',
  'http://www.youtube.com/v/kszLwBaC4Sw?version=3&autohide=1',
  'http://youtu.be/kszLwBaC4Sw',
  'https://www.youtube.com/embed/kszLwBaC4Sw',
  'https://youtube.googleapis.com/v/kszLwBaC4Sw',
  'http://www.youtube.com/watch?v=kszLwBaC4Sw',
  'http://youtu.be/kszLwBaC4Sw',
];

export const vimeoURLS = [
  'https://vimeo.com/32195070',
  'http://vimeo.com/32195070',
  'https://www.vimeo.com/32195070',
  'https://vimeo.com/channels/documentaryfilm/32195070',
  'https://vimeo.com/groups/musicvideo/videos/32195070',
  'https://vimeo.com/32195070?query=foo',
];

export const soundcloudURLS = [
  'https://soundcloud.com/postmalone/rockstar-feat-21-savage',
];

export const notSupportedURLS = [
  // 'www.dailymotion.com/embed/video/x6cskm8',
  // 'http://www.dailymotion.com/embed/video/x6cskm8',
];